-- Reading a table by its columns is not the maker repricing everything in it.
--
-- `openai-pricing` identified a row by the heading above it and the first cell of it. The heading
-- is not unique -- `### Grouped Pricing Table data` appears eight times in one answer and
-- `### Pricing Table data` three -- and the first cell is the group rather than the model in every
-- table shaped `Category | Model | ...`. So the row now carries the processing mode, the modality
-- and any parenthesised ceiling in its id, and the model is taken from the column the table says
-- holds one. On the answer of 2026-10-02 that is 216 rows against the 84 stored, and 82 models
-- against 39: every `gpt-image-*`, `gpt-realtime-*`, `gpt-audio-*`, `gpt-4o*` and the whole
-- o-series had no price here at all, and the Batch price of every fine-tuned model was the Standard
-- one read twice.
--
-- Every stored id therefore changes. `priceWorth` is for a new row and a changed one, so the next
-- collection would otherwise announce 216 models as newly priced and 84 as withdrawn, on a day
-- OpenAI changed nothing. Migration 067 met this and is followed here: `persistCollection` emits
-- neither `new` nor `changed` while a source has no `last_success`, so clearing it makes the next
-- collection one more first collection -- the whole table re-read under the new ids, nobody told.
--
-- `openai-showcase-index` is cleared for the same reason and a smaller one: its tags are now read
-- from the `Models:` list the entry declares instead of from the prose rule, which on the same day
-- took the distinct tags from five to ten. A project whose record gains `gpt-image-2` is not a
-- project retagged by OpenAI.
--
-- Silencing the first collection is not enough on its own, and this was measured on a copy of
-- production rather than reasoned about. `new` and `changed` are guarded by `last_success`;
-- `removed` is not. The 84 rows under the old ids would survive the silent collection as records
-- nothing listed, so the poll after it would hold 297 -- 84 stale and 216 live -- and retaining 216
-- of 297 is a shrink: `persistCollection` raised `CollectionDegradedError` and the source stopped
-- until an operator accepted it. One poll later still, the 84 would have gone out as `removed`.
--
-- So the old rows are dropped here instead. The next collection then meets an empty table under a
-- source with no success, which is exactly the state every source starts in. Prices are missing
-- from `records` between this migration and that collection, about fifteen minutes at the
-- configured rate; `price-moves` and the recap read events, which are untouched, and the rows
-- return in full on the next poll.
--
-- `openai-showcase-index` needs only the silence: a project is identified by its path, so its ids
-- do not move and the arriving tag is a changed body rather than a new record.
--
-- Until each source runs, `silent-sources` reports it as `never_succeeded` and `doctor` counts it
-- among the sources without a success; both correct themselves on the next collection.

DELETE FROM records WHERE source = 'openai-pricing';
UPDATE sources SET last_success = NULL WHERE id IN ('openai-pricing', 'openai-showcase-index');
